
# Build configuration specifically for techlingo-wikilaunchiii project
[build]
  publish = "dist"
  command = "npm run build"
  # Ensure this is the base directory for the main project
  base = "."

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  # Add an environment variable to identify this as the main project
  PROJECT_ID = "techlingo-wikilaunchiii"

# Redirect rule for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly ignore any other directories that might be causing confusion
[build.processing]
  skip_processing = true
