
# Build configuration for the main project only
[build]
  publish = "dist"
  command = "npm run build"

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Redirect rule for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
