
# Build configuration specifically for techlingo-wikilaunchiii project
[build]
  publish = "dist"
  command = "npm run build"
  # Ensure this is the base directory for the main project
  base = "."

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Redirect rule for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

