
name: Supabase CI/CD

on:
  push:
    branches:
      - main

jobs:
  supabase:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Supabase CLI
      run: npm install -g supabase

    - name: Apply Database Migrations
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: supabase db push

    - name: Deploy Functions
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: supabase functions deploy all

    - name: Sync Environment Variables
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: supabase secrets sync

    - name: Run Tests
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: npm test
      
    - name: Upload npm debug log
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: npm-debug-log
        path: /home/runner/.npm/_logs/2025-03-14T20_11_22_702Z-debug.log
